### ISSUE TITLE
你们论文中的实验有认真调过其他框架的性能么？

### ISSUE THREAD

**Issue by hijkzzz** [openpsi-project/ReaLHF#10]
OpenRLHF 的调度缺陷在于 OpenRLHF 会有最高一半的GPU 闲置率
因为我们同时让所有的模型都放在 GPU 上，这是我们目前没有时间去做全异步训练导致的
所以就算极限优化调度性能打满GPU，不考虑更底层的技术优化，只看调度，最多也就让性能翻倍而已
我们提供了调优指南：https://github.com/OpenLLMAI/OpenRLHF?tab=readme-ov-file#performance-tuning-guide

**Comment by garrett4wade** [comment]
您好，非常感谢关注我们的工作。如同我们论文中说的，我们是认真调过其他框架的性能的。

---

对于OpenRLHF，我们采用的是[2024.2.6这个commit下的repo](https://github.com/OpenLLMAI/OpenRLHF/tree/1f52061185ff08d707371375a74a5d36c9110bb1)。您给的链接中主要涉及到了三个方面的优化：

+ Optimized GPU Allocation Strategy

我们根据模型大小做的heuristic GPU划分。因为allocation strategy的空间是指数量级的，我们无法枚举每一种策略并加以测试；ReaL的贡献之一就是通过profiling-based estimation + search engine找到更好的allocation strategy，解决了这个问题。

+ actor/critic & rew/ref colocation

由于大模型训练中GPU是算力受限的，colocate并不会改变GPU计算量。我们确实测试过将这两个option开启，但是没有发现训练速度提升。

+ rew/ref offload

在2024.2.6的commit下，OpenRLHF并没有这个option。

---

我们可以给您分享一些时间上的数据。我们测得OpenRLHF在bs=512, prompt_len=128, gen_len=128, 4 ppo minibatch, no adam offload, actor 34B + critic 7B, 32卡的情况下，一次RLHF iteration的时间最快为94.91s，其中分解如下：

| gen | train | inf | vllm param sync | data transfer/overhead |
| --- | --- | --- | --- | --- |
|5.25 | 51.01  | 19.40  |   8.34   |  10.92 |

如果您发现我们测得的时间显著高于您测得的时间，我们愿意和您深入交流原因并重新跑实验。谢谢！

**Comment by hijkzzz** [comment]
谢谢作者回复，但是我有一些疑问

1. actor/critic & rew/ref colocation
由于大模型训练中GPU是算力受限的，colocate并不会改变GPU计算量。我们确实测试过将这两个option开启，但是没有发现训练速度提升。

任何调度算法都不会减少GPU的计算量，但是可以减少GPU的空置率，如果你们好好调过这个和 rew/ref offload，那么 OpenRLHF 的空置率最多 50%，请问你们如何通过优化调度实现 OpenRLHF 数10倍的性能？

2. 我看你们的代码没有用 vLLM，你们的推理加速如何超越的 vLLM 和 HybridEngine？如果用 DS 和 megatron_core，你们不会有任何的E2E性能优势。因为纯训练框架推理能占 80% 的时间。

3. 如果你们纯用 megatron_core 实现了上述10倍的性能（应该不太可能，megatron_core 推理性能很弱），你们怎么做到无缝兼容 HF Hub?

**Comment by garrett4wade** [comment]
1. 

RLHF的一个iteration的时间，或者FLOP/s，不只归因于GPU的计算。如同论文中图1所示，同样的compute workload在更大的并行度上跑的更慢，因为有并行带来的通信开销。在GPU利用率打满（即要么在算，要么在通信）的情况下，ReaL可以通过重新分布模型参数将通信cost减小，如paper中fig10所示。

关于您说的将rew/ref GPU省下给vllm engine，这是如何分配GPU的问题。我们想说的是在相同分配GPU的策略下colocate不会增加throughput。我们同意您说的观点，也许将vllm engine分配给一半GPU会增加throughput，但这是一种开发者的expert design，希望您理解我们不够聪明，在2月作为用户没有发现这种更好的allocation策略。对应地，ReaL恰恰通过customized search engine解决了更优GPU分配的问题，这是我们的contribution之一，也是ReaL相比OpenRLHF的亮点。

关于与OpenRLHF的性能比较，因为是不同系统end-to-end的比较，所以性能差异来源于多方面。例如，我们支持tensor/pipeline/sequence parallel、模型是重新优化过的、数据通信完全使用NCCL没有CPU-GPU transfer、GAE和parameter reallocation用了自己写的CUDA kernel等等。

如果您想知道排除这些因素后，ReaL相比heuristic策略的比较，我们paper中也说了，是大概20%。这个20%的benefit是parameter reallocation带来的。

4.

> 纯训练框架推理能占 E2E 80% 的时间

这个不一定是对的，很取决于如何设置PPO minibatch数量（因为一个minibatch要train一次，k个minibatch时间近乎增长k倍）以及generate sequence length设置多少。我们论文中采用的是instrgpt的4 ppo minibatch，在34B actor 32卡，prompt_len=128, seqlen=128/384/896的情况下，gen/train时间的比较如下：

| seqlen | gen time | train time |
| --- | --- | --- |
| 896 | 56.5 | 14.7 | 
| 384 | 25.5 | 12.8 |
| 128 | 11.1 | 12.0 |

可以结合上面这个表格和我第一个comment中的表格来看，vllm显然是比我们的推理更快的（11.1s vs 5.25s），在其他setting上也是如此，我们认为更快的原因是vllm用了CUDA graph来减少推理的kernel launching overhead，ReaL并没有用。而hybrid engine本质上是把zero3 layerwise partition变成多个tensor parallel的partition做推理，没有用更好的kernel或CUDA graph，所以和我们的效率是一样的。

我们推理efficient的主要原因，如paper中所说，是通过改变parallel strategy让communication cost减小，导致同样的GPU数量、同样的计算量，我们也能跑得更快。更具体来说，pipelining就比tensor parallel要更好，因为只需要stage之间点对点传输，而tensor parallel需要在每次forward做多次all reduce。我们也重写了huggingface generate让它跑得更快，这是次要原因。

5.

> 然后 RLHF 调度优化算法的意义是什么？

如同paper所说是减少并行带来的通信开销。如果只有一张卡确实意义不大。

> 我直接4个模型轮流加载推理和训练，可以做到0气泡和无需任何调度算法

希望您理解0气泡并不等于GPU达到了峰值FLOP/s。后者是一个复杂的系统优化问题。DSChat也是0气泡，但是OpenRLHF会比DSchat性能更好。

> 你们的调度方案也是需要中途保存ckpt和状态的吗？

如果我理解正确的话，您想问的是除了save/load训练好的模型，需不需要在调度中和disk有交互。这个是不需要的，如同论文中所说，ReaL可以从GPU mesh 1把参数直接redistribute到GPU mesh 2，是GPU显存之间的操作。两个mesh可以overlap，3D parallel strategy也可以不一样。

6.

> 你们测过你们的参数设定下下模型的收敛性/稳定性么？

我们测过，请见[documentation quickstart page](https://openpsi-project.github.io/ReaLHF/quickstart.html#stage-3-ppo)。

我们的learning curve看起来很陡，原因一方面是task（controlled sentiment generation给定一个negative的context就很难生成positive的comment了），另一方面确实是现在版本的代码还有一些bug没修，下周我们会把它们都fix掉。

> 只用 PPO epoch =1 来提升稳定性... prompt_length128, output_length128 比较偏离真实训练场景

算法层面的内容可能见仁见智，调出来的就是好的。我们follow的是intrgpt，您follow的是llama2，我觉得都是对的。

output/prompt length这些参数以及算法的超参数可能对每种task/setting/model都不一样，不存在哪种没意义这么一说。


7.

> 假定你们用纯用 megatron_core 实现了上述10倍的性能

您的这个假定有失偏颇。如上文和paper中所说，相比OpenRLHF，ReaL提升性能的原因有多方面的。因为我们不是基于OpenRLHF的framework而是做end-to-end的比较，所以请原谅我们无法做细节的ablation study。

> 怎么做到无缝兼容 HF Hub？

您可能有些误解，我们说的是seamlessly integreate HF ***checkpoints***，意思是不用checkpoint格式转换就能直接读写，并不是说支持所有的HF模型。当然，Megatron本身并不支持HF格式读写，ReaL中是重新自己实现的。

ReaL中只用了megatron.core的DDP和distributed optimizer，并没有用它实现的模型。如果您有时间，欢迎您阅读我们的代码！

---

如果您还有其他问题，我们非常愿意与您深入讨论！
