### ISSUE TITLE
有多机分布式任务的example吗？

### ISSUE THREAD

**Issue by PKUFlyingPig** [openpsi-project/ReaLHF#24]
nice work！想请问是否有多机的 example 示例或者论文中实验的复现脚本，我看代码似乎是必须用 slurm 起机器是吗？例如我想复现论文中 70B+70B 的 end2end 实验的话能否给出步骤和建议呢，谢谢！

**Comment by garrett4wade** [comment]
Hi你好，感谢关注我们的工作！

我们昨天刚更新了用ray启动分布式的example，您可以clone main上的代码，然后去看下[新的doc](https://openpsi-project.github.io/ReaLHF/distributed.html)。

简单来说，按照ray的教程setup ray cluster之后，examples文件夹下面的script把mode设成ray就可以跑了。

在杀了实验之后，请记得在每个节点上重启下ray，不然ray的进程会stale，再起下一个实验会卡住。

**Comment by PKUFlyingPig** [comment]
另外，很想更细致地学习你们代码的架构，目前 codebase 比较庞杂而且似乎backend既有megatron-lm 也有 deepspeed。分布式任务虽然能用ray启动但似乎代码里没有看到 ray actor 相关的 code，具体是怎么通过 ray 来分配的资源的呢？请问能否提供一个简洁明了并且 high-level 的 code architecture 的描述从而可以更好地学习你们的工作。我看到文档是有[相关的章节](https://openpsi-project.github.io/ReaLHF/arch.html) 的但是似乎还未施工。另外再次感谢开源这么好的工作。

**Comment by garrett4wade** [comment]
还有个事情是用`meta-llama/Llama-2-7b`这个identifier很可能不work，因为ReaL需要根据pytorch_model.bin.index.json来找每个LLM shard到底需要load哪些文件。请先把模型下载下来然后把路径传进去。

**Comment by garrett4wade** [comment]
Hi, we have updated our documentation recently. Do you have any additional concerns about the code architecture and launching the code?

**Comment by PKUFlyingPig** [comment]
Thanks for your patient answers and it runs smoothly on my infra—respect for your guys' nice work.
