### ISSUE TITLE
如何推理

### ISSUE THREAD

**Issue by AIRobotZhang** [openpsi-project/ReaLHF#40]
现有框架如何在PPO训练完成后，加载模型在测试集上进行推理

**Comment by garrett4wade** [comment]
Three options:

+ Use HuggingFace `AutoModelForCausalLM.from_pretrained("your/checkpoint/path")` and do inference following the API of `transformers`.

+ Use vLLM to load the saved checkpoint. Please check vLLM tutorials for details. Note that this requires your code is after [this commit](https://github.com/openpsi-project/ReaLHF/commit/f9c73c096c4ef94a61ec3cf45008980faf7ef0ec), which amends an `architectures` attribute to the huggingface config (see [here](https://github.com/openpsi-project/ReaLHF/blob/main/realhf/api/from_hf/llama.py#L268)). If you are using a previous version, you should manually copy the `config.json` from the base model to your saved checkpoint path.

+ Use our [provided generation script](https://github.com/openpsi-project/ReaLHF/blob/main/examples/scripts/local/gen.sh), but you need to modify the [generation interface](https://github.com/openpsi-project/ReaLHF/blob/main/realhf/impl/model/interface/gen_interface.py) to save generated results properly.

The latter two solutions should be way fater than the first solution.

**Comment by AIRobotZhang** [comment]
Thank you!
