### ISSUE TITLE
TransformerConfig() takes no arguments

### ISSUE THREAD

**Issue by AIRobotZhang** [openpsi-project/ReaLHF#46]
When I run sft according to the tutorial, I encounter the following error case:

20240723-13:09:26.013 Prompt Answer Dataset INFO: Loaded Prompt Answer Dataset with INFO: #seqs=4000, truncation length=1024, avg prompt length=10.1, avg answer length=286.9
20240723-13:09:26.781 model_worker-worker INFO: Making model ModelName(role='default', replica_id=0)...
20240723-13:10:44.396 Prompt Answer Dataset INFO: Loaded Prompt Answer Dataset with INFO: #seqs=1000, truncation length=1024, avg prompt length=10.1, avg answer length=285.5
20240723-13:10:44.600 Prompt Answer Dataset INFO: Loaded Prompt Answer Dataset with INFO: #seqs=1000, truncation length=1024, avg prompt length=10.1, avg answer length=285.5
20240723-13:10:44.641 master_worker-worker INFO: Initialize model backends with order: [ModelName(role='default', replica_id=0)].
20240723-13:10:44.641 benchmark DEBUG: master worker #request_all# *end* time $1721711444641630392$
20240723-13:10:44.692 benchmark DEBUG: Request "initialize" time in total: 0.0509s, 0.0254s per request
20240723-13:10:44.692 worker ERROR: Worker encountered error TransformerConfig() takes no arguments
Traceback (most recent call last):
  File "/root/ReaLHF/realhf/system/worker_base.py", line 631, in run
    r = self._poll()
  File "/root/ReaLHF/realhf/system/model_worker.py", line 824, in _poll
    self.model_poll_step(request, data, handled, res)
  File "/root/ReaLHF/realhf/system/model_worker.py", line 549, in model_poll_step
    self.__models[request.handler.model_name] = self._backend.initialize(
  File "/root/ReaLHF/realhf/api/core/model_api.py", line 335, in initialize
    return self._initialize(model, spec)
  File "/root/ReaLHF/realhf/impl/model/backend/megatron.py", line 840, in _initialize
    config=get_megatron_transformer_config(module.config),
  File "/root/ReaLHF/realhf/impl/model/backend/megatron.py", line 125, in get_megatron_transformer_config
    return TransformerConfig(
TypeError: TransformerConfig() takes no arguments

**Comment by nuzant** [comment]
It seems package `megatron_core` is not properly installed in your environment. In `megatron.py` if `megatron.core` can not be successfully imported `TransformerConfig` class will fallback to a dummy class that cannot be initialized properly.

**Comment by garrett4wade** [comment]
Closed due to inactivity.
